name: gaussian_splatting_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - python=3.10.12
  - pip>=24.0.0
  - numpy==1.25.1
  - Pillow==9.3.0
  - plyfile==1.0.3
  - tqdm==4.65.0
  - pandas==2.0.1
  - sympy==1.11.1
  - ConfigArgParse==1.5.3
  - omegaconf==2.3.0
  - scipy==1.10.1
  - matplotlib==3.7.1
  - setuptools==60.2.0
  - imageio==2.28.1
  - h5py==3.8.0
  - scikit-learn==1.2.2
  - albumentations==1.3.1
  - timm==0.9.10
  - fvcore==0.1.5.post20221221
  - scikit-image==0.20.0
  - mediapy==1.2.2
  - trimesh==3.22.0
  - pytorch==2.2.0
  - torchvision==0.17.0
  - torchaudio==2.2.0
  - pytorch-cuda=11.8
  - kornia==0.7.0
  - torchmetrics==0.11.4
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
